services:
    frontend:
        build:
            context: .
        environment:
            - NODE_ENV=production
            - IN_CONTAINER=true
        ports:
            - 50000:80 # .com
            - 50001:81 # .nl
    backend:
        image: ghcr.io/jonathanbout/portfolio-backend
        env_file: backend.compose.env
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:5000
            - CORS_ALLOWED_ORIGINS=http://localhost:50000,http://localhost:50001
            - ConnectionStrings__Postgres=Host=db;Port=5432;Database=portfolio;Username=postgres;Password=postgres
        ports:
            - 3998:5000
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=portfolio