services:
    server:
        build:
            context: .
        environment:
            NODE_ENV: production
            IN_CONTAINER: true
        ports:
            - 50000:80 # .com
            - 50001:81 # .nl
